// Autogenerated. Do not modify.
//
// This file can be regenerated by running
// go run github.com/arnavdugar/hsm/codegen -i=machine.yaml -o=machine.go

package simple

import "github.com/arnavdugar/hsm/runtime"

type ActionType int

const ActionNext ActionType = 1

type StateType int

const (
	StateA StateType = 1
	StateB StateType = 2
	StateC StateType = 3
)

type Handler interface {
}

// Handles an action and returns the destination state or an error.
func Handle(handler Handler, state StateType, action ActionType, data interface{}) (StateType, error) {
	switch action {
	case ActionNext:
		return HandleNext(handler, state)
	default:
		return state, runtime.ErrUnknownAction
	}
}

// Handles a "Next" action and returns the destination state or an error.
func HandleNext(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateA:
		return StateB, nil
	case StateB:
		return StateC, nil
	case StateC:
		return StateA, nil
	default:
		return state, runtime.ErrUnknownState
	}
	return state, runtime.ErrNoTransition
}
