// Code generated by hsm/codegen. DO NOT EDIT.
//
// This file can be regenerated by running
// go run github.com/arnavdugar/hsm/codegen -i=machine.yaml -o=machine.go

package combinationlock

import "github.com/arnavdugar/hsm/runtime"

type ActionType int

const (
	ActionDigit ActionType = 1
	ActionLock  ActionType = 2
)

type StateType int

const (
	StateLocked      StateType = 1
	StateFirstDigit  StateType = 2
	StateSecondDigit StateType = 3
	StateUnlocked    StateType = 4
)

type Handler interface {
	IsFirstDigit(data int) (bool, error)
	IsSecondDigit(data int) (bool, error)
	IsThirdDigit(data int) (bool, error)
}

// Handles an action and returns the destination state or an error.
func Handle(handler Handler, state StateType, action ActionType, data any) (StateType, error) {
	switch action {
	case ActionDigit:
		actionData, ok := data.(int)
		if !ok && (data != nil || any(actionData) != nil) {
			return state, runtime.ErrInvalidActionDataType
		}
		return HandleDigit(handler, state, actionData)
	case ActionLock:
		return HandleLock(handler, state)
	default:
		return state, runtime.ErrUnknownAction
	}
}

// Handles a "Digit" action and returns the destination state or an error.
func HandleDigit(handler Handler, state StateType, data int) (StateType, error) {
	switch state {
	case StateLocked:
		{
			status, err := handler.IsFirstDigit(data)
			if err != nil {
				return state, err
			}
			if status {
				return StateFirstDigit, nil
			}
		}
		return StateLocked, nil
	case StateFirstDigit:
		{
			status, err := handler.IsSecondDigit(data)
			if err != nil {
				return state, err
			}
			if status {
				return StateSecondDigit, nil
			}
		}
		return StateLocked, nil
	case StateSecondDigit:
		{
			status, err := handler.IsThirdDigit(data)
			if err != nil {
				return state, err
			}
			if status {
				return StateUnlocked, nil
			}
		}
		return StateLocked, nil
	case StateUnlocked:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Lock" action and returns the destination state or an error.
func HandleLock(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateUnlocked:
		return StateLocked, nil
	case StateLocked, StateFirstDigit, StateSecondDigit:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}
