// Code generated by MockGen. DO NOT EDIT.
// Source: machine.go
//
// Generated by this command:
//
//	mockgen -source=machine.go -destination=machine_mock_test.go -package combinationlock
//

// Package combinationlock is a generated GoMock package.
package combinationlock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// IsFirstDigit mocks base method.
func (m *MockHandler) IsFirstDigit(data int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFirstDigit", data)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFirstDigit indicates an expected call of IsFirstDigit.
func (mr *MockHandlerMockRecorder) IsFirstDigit(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFirstDigit", reflect.TypeOf((*MockHandler)(nil).IsFirstDigit), data)
}

// IsSecondDigit mocks base method.
func (m *MockHandler) IsSecondDigit(data int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSecondDigit", data)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSecondDigit indicates an expected call of IsSecondDigit.
func (mr *MockHandlerMockRecorder) IsSecondDigit(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSecondDigit", reflect.TypeOf((*MockHandler)(nil).IsSecondDigit), data)
}

// IsThirdDigit mocks base method.
func (m *MockHandler) IsThirdDigit(data int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsThirdDigit", data)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsThirdDigit indicates an expected call of IsThirdDigit.
func (mr *MockHandlerMockRecorder) IsThirdDigit(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsThirdDigit", reflect.TypeOf((*MockHandler)(nil).IsThirdDigit), data)
}
