// Code generated by hsm/codegen. DO NOT EDIT.
//
// This file can be regenerated by running
// go run github.com/arnavdugar/hsm/codegen -i=machine.yaml -o=machine.go

package rollback

import "github.com/arnavdugar/hsm/runtime"

type ActionType int

const (
	ActionReserved  ActionType = 1
	ActionFailure   ActionType = 2
	ActionCharged   ActionType = 3
	ActionFulfilled ActionType = 4
	ActionRefunded  ActionType = 5
	ActionReleased  ActionType = 6
)

type StateType int

const (
	StateReserve            StateType = 1
	StateCharge             StateType = 2
	StateFulfill            StateType = 3
	StateRefund             StateType = 4
	StateReleaseReservation StateType = 5
	StateCompleted          StateType = 6
	StateFailed             StateType = 7
)

type Handler interface {
}

// Handles an action and returns the destination state or an error.
func Handle(handler Handler, state StateType, action ActionType, data interface{}) (StateType, error) {
	switch action {
	case ActionReserved:
		return HandleReserved(handler, state)
	case ActionFailure:
		return HandleFailure(handler, state)
	case ActionCharged:
		return HandleCharged(handler, state)
	case ActionFulfilled:
		return HandleFulfilled(handler, state)
	case ActionRefunded:
		return HandleRefunded(handler, state)
	case ActionReleased:
		return HandleReleased(handler, state)
	default:
		return state, runtime.ErrUnknownAction
	}
}

// Handles a "Reserved" action and returns the destination state or an error.
func HandleReserved(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateReserve:
		return StateCharge, nil
	case StateCharge, StateFulfill, StateRefund, StateReleaseReservation, StateCompleted, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Failure" action and returns the destination state or an error.
func HandleFailure(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateReserve:
		return StateFailed, nil
	case StateCharge:
		return StateReleaseReservation, nil
	case StateFulfill:
		return StateRefund, nil
	case StateRefund, StateReleaseReservation, StateCompleted, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Charged" action and returns the destination state or an error.
func HandleCharged(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateCharge:
		return StateFulfill, nil
	case StateReserve, StateFulfill, StateRefund, StateReleaseReservation, StateCompleted, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Fulfilled" action and returns the destination state or an error.
func HandleFulfilled(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateFulfill:
		return StateCompleted, nil
	case StateReserve, StateCharge, StateRefund, StateReleaseReservation, StateCompleted, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Refunded" action and returns the destination state or an error.
func HandleRefunded(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateRefund:
		return StateReleaseReservation, nil
	case StateReserve, StateCharge, StateFulfill, StateReleaseReservation, StateCompleted, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Released" action and returns the destination state or an error.
func HandleReleased(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateReleaseReservation:
		return StateFailed, nil
	case StateReserve, StateCharge, StateFulfill, StateRefund, StateCompleted, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}
