// Code generated by hsm/codegen. DO NOT EDIT.
//
// This file can be regenerated by running
// go run github.com/arnavdugar/hsm/codegen -i=machine.yaml -o=machine.go

package tcp

import "github.com/arnavdugar/hsm/runtime"

type ActionType int

const (
	ActionActiveOpen    ActionType = 1
	ActionPassiveOpen   ActionType = 2
	ActionReceiveSyn    ActionType = 3
	ActionSend          ActionType = 4
	ActionClose         ActionType = 5
	ActionReceiveSynAck ActionType = 6
	ActionReceiveAck    ActionType = 7
	ActionReceiveFin    ActionType = 8
	ActionReceiveFinAck ActionType = 9
	ActionTimeout       ActionType = 10
)

type StateType int

const (
	StateClosed      StateType = 1
	StateListen      StateType = 2
	StateSynSent     StateType = 3
	StateSynReceived StateType = 4
	StateEstablished StateType = 5
	StateFinWait1    StateType = 6
	StateFinWait2    StateType = 7
	StateCloseWait   StateType = 8
	StateClosing     StateType = 9
	StateLastAck     StateType = 10
	StateTimeWait    StateType = 11
)

type Handler interface {
}

// Handles an action and returns the destination state or an error.
func Handle(handler Handler, state StateType, action ActionType, data any) (StateType, error) {
	switch action {
	case ActionActiveOpen:
		return HandleActiveOpen(handler, state)
	case ActionPassiveOpen:
		return HandlePassiveOpen(handler, state)
	case ActionReceiveSyn:
		return HandleReceiveSyn(handler, state)
	case ActionSend:
		return HandleSend(handler, state)
	case ActionClose:
		return HandleClose(handler, state)
	case ActionReceiveSynAck:
		return HandleReceiveSynAck(handler, state)
	case ActionReceiveAck:
		return HandleReceiveAck(handler, state)
	case ActionReceiveFin:
		return HandleReceiveFin(handler, state)
	case ActionReceiveFinAck:
		return HandleReceiveFinAck(handler, state)
	case ActionTimeout:
		return HandleTimeout(handler, state)
	default:
		return state, runtime.ErrUnknownAction
	}
}

// Handles a "ActiveOpen" action and returns the destination state or an error.
func HandleActiveOpen(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateClosed:
		return StateSynSent, nil
	case StateListen, StateSynSent, StateSynReceived, StateEstablished, StateFinWait1, StateFinWait2, StateCloseWait, StateClosing, StateLastAck, StateTimeWait:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "PassiveOpen" action and returns the destination state or an error.
func HandlePassiveOpen(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateClosed:
		return StateListen, nil
	case StateListen, StateSynSent, StateSynReceived, StateEstablished, StateFinWait1, StateFinWait2, StateCloseWait, StateClosing, StateLastAck, StateTimeWait:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "ReceiveSyn" action and returns the destination state or an error.
func HandleReceiveSyn(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateListen:
		return StateSynReceived, nil
	case StateSynSent:
		return StateSynReceived, nil
	case StateClosed, StateSynReceived, StateEstablished, StateFinWait1, StateFinWait2, StateCloseWait, StateClosing, StateLastAck, StateTimeWait:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Send" action and returns the destination state or an error.
func HandleSend(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateListen:
		return StateSynSent, nil
	case StateClosed, StateSynSent, StateSynReceived, StateEstablished, StateFinWait1, StateFinWait2, StateCloseWait, StateClosing, StateLastAck, StateTimeWait:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Close" action and returns the destination state or an error.
func HandleClose(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateListen:
		return StateClosed, nil
	case StateSynSent:
		return StateClosed, nil
	case StateSynReceived:
		return StateFinWait1, nil
	case StateEstablished:
		return StateFinWait1, nil
	case StateCloseWait:
		return StateLastAck, nil
	case StateClosed, StateFinWait1, StateFinWait2, StateClosing, StateLastAck, StateTimeWait:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "ReceiveSynAck" action and returns the destination state or an error.
func HandleReceiveSynAck(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateSynSent:
		return StateEstablished, nil
	case StateClosed, StateListen, StateSynReceived, StateEstablished, StateFinWait1, StateFinWait2, StateCloseWait, StateClosing, StateLastAck, StateTimeWait:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "ReceiveAck" action and returns the destination state or an error.
func HandleReceiveAck(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateSynReceived:
		return StateEstablished, nil
	case StateFinWait1:
		return StateFinWait2, nil
	case StateClosing:
		return StateTimeWait, nil
	case StateLastAck:
		return StateClosed, nil
	case StateClosed, StateListen, StateSynSent, StateEstablished, StateFinWait2, StateCloseWait, StateTimeWait:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "ReceiveFin" action and returns the destination state or an error.
func HandleReceiveFin(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateEstablished:
		return StateCloseWait, nil
	case StateFinWait1:
		return StateClosing, nil
	case StateFinWait2:
		return StateTimeWait, nil
	case StateClosed, StateListen, StateSynSent, StateSynReceived, StateCloseWait, StateClosing, StateLastAck, StateTimeWait:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "ReceiveFinAck" action and returns the destination state or an error.
func HandleReceiveFinAck(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateFinWait1:
		return StateTimeWait, nil
	case StateClosed, StateListen, StateSynSent, StateSynReceived, StateEstablished, StateFinWait2, StateCloseWait, StateClosing, StateLastAck, StateTimeWait:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Timeout" action and returns the destination state or an error.
func HandleTimeout(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateTimeWait:
		return StateClosed, nil
	case StateClosed, StateListen, StateSynSent, StateSynReceived, StateEstablished, StateFinWait1, StateFinWait2, StateCloseWait, StateClosing, StateLastAck:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}
