// Code generated by MockGen. DO NOT EDIT.
// Source: machine.go
//
// Generated by this command:
//
//	mockgen -source=machine.go -destination=machine_mock_test.go -package connectionmanager
//

// Package connectionmanager is a generated GoMock package.
package connectionmanager

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// CanRetry mocks base method.
func (m *MockHandler) CanRetry() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanRetry")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanRetry indicates an expected call of CanRetry.
func (mr *MockHandlerMockRecorder) CanRetry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanRetry", reflect.TypeOf((*MockHandler)(nil).CanRetry))
}

// RecordRetry mocks base method.
func (m *MockHandler) RecordRetry() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRetry")
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRetry indicates an expected call of RecordRetry.
func (mr *MockHandlerMockRecorder) RecordRetry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRetry", reflect.TypeOf((*MockHandler)(nil).RecordRetry))
}

// ResetRetries mocks base method.
func (m *MockHandler) ResetRetries() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetRetries")
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetRetries indicates an expected call of ResetRetries.
func (mr *MockHandlerMockRecorder) ResetRetries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetRetries", reflect.TypeOf((*MockHandler)(nil).ResetRetries))
}

// StartSession mocks base method.
func (m *MockHandler) StartSession() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession")
	ret0, _ := ret[0].(error)
	return ret0
}

// StartSession indicates an expected call of StartSession.
func (mr *MockHandlerMockRecorder) StartSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockHandler)(nil).StartSession))
}
