// Code generated by hsm/codegen. DO NOT EDIT.
//
// This file can be regenerated by running
// go run github.com/arnavdugar/hsm/codegen -i=machine.yaml -o=machine.go

package connectionmanager

import "github.com/arnavdugar/hsm/runtime"

type ActionType int

const (
	ActionConnect        ActionType = 1
	ActionTransportReady ActionType = 2
	ActionFailure        ActionType = 3
	ActionAuthenticated  ActionType = 4
	ActionConnectionLost ActionType = 5
	ActionDisconnect     ActionType = 6
	ActionTimeout        ActionType = 7
)

type StateType int

const (
	StateDisconnected   StateType = 1
	StateConnecting     StateType = 2
	StateAuthenticating StateType = 3
	StateConnected      StateType = 4
	StateBackoff        StateType = 5
	StateFailed         StateType = 6
)

type Handler interface {
	StartSession() error
	ResetRetries() error
	CanRetry() (bool, error)
	RecordRetry() error
}

// Handles an action and returns the destination state or an error.
func Handle(handler Handler, state StateType, action ActionType, data any) (StateType, error) {
	switch action {
	case ActionConnect:
		return HandleConnect(handler, state)
	case ActionTransportReady:
		return HandleTransportReady(handler, state)
	case ActionFailure:
		return HandleFailure(handler, state)
	case ActionAuthenticated:
		return HandleAuthenticated(handler, state)
	case ActionConnectionLost:
		return HandleConnectionLost(handler, state)
	case ActionDisconnect:
		return HandleDisconnect(handler, state)
	case ActionTimeout:
		return HandleTimeout(handler, state)
	default:
		return state, runtime.ErrUnknownAction
	}
}

// Handles a "Connect" action and returns the destination state or an error.
func HandleConnect(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateDisconnected:
		{
			err := handler.StartSession()
			if err != nil {
				return state, err
			}
		}
		return StateConnecting, nil
	case StateConnecting, StateAuthenticating, StateConnected, StateBackoff, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "TransportReady" action and returns the destination state or an error.
func HandleTransportReady(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateConnecting:
		return StateAuthenticating, nil
	case StateDisconnected, StateAuthenticating, StateConnected, StateBackoff, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Failure" action and returns the destination state or an error.
func HandleFailure(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateConnecting:
		return StateBackoff, nil
	case StateAuthenticating:
		return StateBackoff, nil
	case StateDisconnected, StateConnected, StateBackoff, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Authenticated" action and returns the destination state or an error.
func HandleAuthenticated(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateAuthenticating:
		{
			err := handler.ResetRetries()
			if err != nil {
				return state, err
			}
		}
		return StateConnected, nil
	case StateDisconnected, StateConnecting, StateConnected, StateBackoff, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "ConnectionLost" action and returns the destination state or an error.
func HandleConnectionLost(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateConnected:
		return StateBackoff, nil
	case StateDisconnected, StateConnecting, StateAuthenticating, StateBackoff, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Disconnect" action and returns the destination state or an error.
func HandleDisconnect(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateConnected:
		return StateDisconnected, nil
	case StateBackoff:
		return StateDisconnected, nil
	case StateDisconnected, StateConnecting, StateAuthenticating, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Timeout" action and returns the destination state or an error.
func HandleTimeout(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateBackoff:
		{
			status, err := handler.CanRetry()
			if err != nil {
				return state, err
			}
			if status {
				{
					err := handler.RecordRetry()
					if err != nil {
						return state, err
					}
				}
				return StateConnecting, nil
			}
		}
		return StateFailed, nil
	case StateDisconnected, StateConnecting, StateAuthenticating, StateConnected, StateFailed:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}
