// Code generated by MockGen. DO NOT EDIT.
// Source: machine.go
//
// Generated by this command:
//
//	mockgen -source=machine.go -destination=machine_mock_test.go -package group
//

// Package group is a generated GoMock package.
package group

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// CanRefresh mocks base method.
func (m *MockHandler) CanRefresh(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanRefresh", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanRefresh indicates an expected call of CanRefresh.
func (mr *MockHandlerMockRecorder) CanRefresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanRefresh", reflect.TypeOf((*MockHandler)(nil).CanRefresh), ctx)
}

// CanRetryConnecting mocks base method.
func (m *MockHandler) CanRetryConnecting(ctx context.Context, data int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanRetryConnecting", ctx, data)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanRetryConnecting indicates an expected call of CanRetryConnecting.
func (mr *MockHandlerMockRecorder) CanRetryConnecting(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanRetryConnecting", reflect.TypeOf((*MockHandler)(nil).CanRetryConnecting), ctx, data)
}

// CanRetryState mocks base method.
func (m *MockHandler) CanRetryState(ctx context.Context, data int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanRetryState", ctx, data)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanRetryState indicates an expected call of CanRetryState.
func (mr *MockHandlerMockRecorder) CanRetryState(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanRetryState", reflect.TypeOf((*MockHandler)(nil).CanRetryState), ctx, data)
}

// CanRetryTransport mocks base method.
func (m *MockHandler) CanRetryTransport(ctx context.Context, data int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanRetryTransport", ctx, data)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanRetryTransport indicates an expected call of CanRetryTransport.
func (mr *MockHandlerMockRecorder) CanRetryTransport(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanRetryTransport", reflect.TypeOf((*MockHandler)(nil).CanRetryTransport), ctx, data)
}

// EnterAuthenticating mocks base method.
func (m *MockHandler) EnterAuthenticating(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterAuthenticating", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnterAuthenticating indicates an expected call of EnterAuthenticating.
func (mr *MockHandlerMockRecorder) EnterAuthenticating(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterAuthenticating", reflect.TypeOf((*MockHandler)(nil).EnterAuthenticating), ctx)
}

// EnterConnecting mocks base method.
func (m *MockHandler) EnterConnecting(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterConnecting", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnterConnecting indicates an expected call of EnterConnecting.
func (mr *MockHandlerMockRecorder) EnterConnecting(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterConnecting", reflect.TypeOf((*MockHandler)(nil).EnterConnecting), ctx)
}

// EnterDialing mocks base method.
func (m *MockHandler) EnterDialing(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterDialing", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnterDialing indicates an expected call of EnterDialing.
func (mr *MockHandlerMockRecorder) EnterDialing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterDialing", reflect.TypeOf((*MockHandler)(nil).EnterDialing), ctx)
}

// EnterDraining mocks base method.
func (m *MockHandler) EnterDraining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterDraining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnterDraining indicates an expected call of EnterDraining.
func (mr *MockHandlerMockRecorder) EnterDraining(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterDraining", reflect.TypeOf((*MockHandler)(nil).EnterDraining), ctx)
}

// EnterOffline mocks base method.
func (m *MockHandler) EnterOffline(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterOffline", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnterOffline indicates an expected call of EnterOffline.
func (mr *MockHandlerMockRecorder) EnterOffline(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterOffline", reflect.TypeOf((*MockHandler)(nil).EnterOffline), ctx)
}

// EnterReady mocks base method.
func (m *MockHandler) EnterReady(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterReady", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnterReady indicates an expected call of EnterReady.
func (mr *MockHandlerMockRecorder) EnterReady(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterReady", reflect.TypeOf((*MockHandler)(nil).EnterReady), ctx)
}

// EnterSession mocks base method.
func (m *MockHandler) EnterSession(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterSession", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnterSession indicates an expected call of EnterSession.
func (mr *MockHandlerMockRecorder) EnterSession(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterSession", reflect.TypeOf((*MockHandler)(nil).EnterSession), ctx)
}

// EnterTransport mocks base method.
func (m *MockHandler) EnterTransport(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterTransport", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnterTransport indicates an expected call of EnterTransport.
func (mr *MockHandlerMockRecorder) EnterTransport(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterTransport", reflect.TypeOf((*MockHandler)(nil).EnterTransport), ctx)
}

// ExitAuthenticating mocks base method.
func (m *MockHandler) ExitAuthenticating(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitAuthenticating", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitAuthenticating indicates an expected call of ExitAuthenticating.
func (mr *MockHandlerMockRecorder) ExitAuthenticating(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitAuthenticating", reflect.TypeOf((*MockHandler)(nil).ExitAuthenticating), ctx)
}

// ExitConnecting mocks base method.
func (m *MockHandler) ExitConnecting(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitConnecting", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitConnecting indicates an expected call of ExitConnecting.
func (mr *MockHandlerMockRecorder) ExitConnecting(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitConnecting", reflect.TypeOf((*MockHandler)(nil).ExitConnecting), ctx)
}

// ExitDialing mocks base method.
func (m *MockHandler) ExitDialing(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitDialing", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitDialing indicates an expected call of ExitDialing.
func (mr *MockHandlerMockRecorder) ExitDialing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitDialing", reflect.TypeOf((*MockHandler)(nil).ExitDialing), ctx)
}

// ExitDraining mocks base method.
func (m *MockHandler) ExitDraining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitDraining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitDraining indicates an expected call of ExitDraining.
func (mr *MockHandlerMockRecorder) ExitDraining(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitDraining", reflect.TypeOf((*MockHandler)(nil).ExitDraining), ctx)
}

// ExitOffline mocks base method.
func (m *MockHandler) ExitOffline(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitOffline", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitOffline indicates an expected call of ExitOffline.
func (mr *MockHandlerMockRecorder) ExitOffline(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitOffline", reflect.TypeOf((*MockHandler)(nil).ExitOffline), ctx)
}

// ExitReady mocks base method.
func (m *MockHandler) ExitReady(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitReady", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitReady indicates an expected call of ExitReady.
func (mr *MockHandlerMockRecorder) ExitReady(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitReady", reflect.TypeOf((*MockHandler)(nil).ExitReady), ctx)
}

// ExitSession mocks base method.
func (m *MockHandler) ExitSession(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitSession", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitSession indicates an expected call of ExitSession.
func (mr *MockHandlerMockRecorder) ExitSession(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitSession", reflect.TypeOf((*MockHandler)(nil).ExitSession), ctx)
}

// ExitTransport mocks base method.
func (m *MockHandler) ExitTransport(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitTransport", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitTransport indicates an expected call of ExitTransport.
func (mr *MockHandlerMockRecorder) ExitTransport(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitTransport", reflect.TypeOf((*MockHandler)(nil).ExitTransport), ctx)
}

// ResetSession mocks base method.
func (m *MockHandler) ResetSession(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetSession", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetSession indicates an expected call of ResetSession.
func (mr *MockHandlerMockRecorder) ResetSession(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetSession", reflect.TypeOf((*MockHandler)(nil).ResetSession), ctx)
}

// RetryConnecting mocks base method.
func (m *MockHandler) RetryConnecting(ctx context.Context, data int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryConnecting", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryConnecting indicates an expected call of RetryConnecting.
func (mr *MockHandlerMockRecorder) RetryConnecting(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryConnecting", reflect.TypeOf((*MockHandler)(nil).RetryConnecting), ctx, data)
}

// RetrySession mocks base method.
func (m *MockHandler) RetrySession(ctx context.Context, data int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrySession", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetrySession indicates an expected call of RetrySession.
func (mr *MockHandlerMockRecorder) RetrySession(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrySession", reflect.TypeOf((*MockHandler)(nil).RetrySession), ctx, data)
}

// RetryState mocks base method.
func (m *MockHandler) RetryState(ctx context.Context, data int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryState", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryState indicates an expected call of RetryState.
func (mr *MockHandlerMockRecorder) RetryState(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryState", reflect.TypeOf((*MockHandler)(nil).RetryState), ctx, data)
}

// RetryTransport mocks base method.
func (m *MockHandler) RetryTransport(ctx context.Context, data int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryTransport", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryTransport indicates an expected call of RetryTransport.
func (mr *MockHandlerMockRecorder) RetryTransport(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryTransport", reflect.TypeOf((*MockHandler)(nil).RetryTransport), ctx, data)
}
