// Code generated by hsm/codegen. DO NOT EDIT.
//
// This file can be regenerated by running
// go run github.com/arnavdugar/hsm/codegen -i=machine.yaml -o=machine.go

package group

import (
	"context"
	"github.com/arnavdugar/hsm/runtime"
)

type ActionType int

const (
	ActionStart   ActionType = 1
	ActionDirect  ActionType = 2
	ActionNext    ActionType = 3
	ActionRetry   ActionType = 4
	ActionRestart ActionType = 5
	ActionReset   ActionType = 6
	ActionRefresh ActionType = 7
	ActionClose   ActionType = 8
)

type StateType int

const (
	StateOffline        StateType = 1
	StateDialing        StateType = 2
	StateAuthenticating StateType = 3
	StateReady          StateType = 4
	StateDraining       StateType = 5
)

type Handler interface {
	CanRetryState(ctx context.Context, data int) (bool, error)
	CanRetryConnecting(ctx context.Context, data int) (bool, error)
	CanRetryTransport(ctx context.Context, data int) (bool, error)
	RetryState(ctx context.Context, data int) error
	RetrySession(ctx context.Context, data int) error
	RetryConnecting(ctx context.Context, data int) error
	RetryTransport(ctx context.Context, data int) error
	ResetSession(ctx context.Context) error
	CanRefresh(ctx context.Context) (bool, error)
	EnterOffline(ctx context.Context) error
	ExitOffline(ctx context.Context) error
	EnterDialing(ctx context.Context) error
	ExitDialing(ctx context.Context) error
	EnterAuthenticating(ctx context.Context) error
	ExitAuthenticating(ctx context.Context) error
	EnterReady(ctx context.Context) error
	ExitReady(ctx context.Context) error
	EnterDraining(ctx context.Context) error
	ExitDraining(ctx context.Context) error
	EnterSession(ctx context.Context) error
	ExitSession(ctx context.Context) error
	EnterConnecting(ctx context.Context) error
	ExitConnecting(ctx context.Context) error
	EnterTransport(ctx context.Context) error
	ExitTransport(ctx context.Context) error
}

// Handles an action and returns the destination state or an error.
func Handle(ctx context.Context, handler Handler, state StateType, action ActionType, data any) (StateType, error) {
	switch action {
	case ActionStart:
		return HandleStart(ctx, handler, state)
	case ActionDirect:
		return HandleDirect(ctx, handler, state)
	case ActionNext:
		return HandleNext(ctx, handler, state)
	case ActionRetry:
		actionData, ok := data.(int)
		if !ok {
			return state, runtime.ErrInvalidActionDataType
		}
		return HandleRetry(ctx, handler, state, actionData)
	case ActionRestart:
		return HandleRestart(ctx, handler, state)
	case ActionReset:
		return HandleReset(ctx, handler, state)
	case ActionRefresh:
		return HandleRefresh(ctx, handler, state)
	case ActionClose:
		return HandleClose(ctx, handler, state)
	default:
		return state, runtime.ErrUnknownAction
	}
}

// Handles a "Start" action and returns the destination state or an error.
func HandleStart(ctx context.Context, handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateOffline:
		{
			err := handler.ExitOffline(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateDialing, StateAuthenticating, StateReady, StateDraining:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Direct" action and returns the destination state or an error.
func HandleDirect(ctx context.Context, handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateOffline:
		{
			err := handler.ExitOffline(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterAuthenticating(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateAuthenticating, nil
	case StateDialing, StateAuthenticating, StateReady, StateDraining:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Next" action and returns the destination state or an error.
func HandleNext(ctx context.Context, handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateDialing:
		{
			err := handler.ExitDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterAuthenticating(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateAuthenticating, nil
	case StateAuthenticating:
		{
			err := handler.ExitAuthenticating(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterReady(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateReady, nil
	case StateReady:
		{
			err := handler.ExitReady(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDraining(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDraining, nil
	case StateDraining:
		{
			err := handler.ExitDraining(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterOffline(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateOffline, nil
	case StateOffline:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Retry" action and returns the destination state or an error.
func HandleRetry(ctx context.Context, handler Handler, state StateType, data int) (StateType, error) {
	switch state {
	case StateDialing:
		{
			status, err := handler.CanRetryConnecting(ctx, data)
			if err != nil {
				return state, err
			}
			if status {
				{
					err := handler.ExitDialing(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.RetryConnecting(ctx, data)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.EnterDialing(ctx)
					if err != nil {
						return state, err
					}
				}
				return StateDialing, nil
			}
		}
		{
			err := handler.ExitDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.RetrySession(ctx, data)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateAuthenticating:
		{
			status, err := handler.CanRetryState(ctx, data)
			if err != nil {
				return state, err
			}
			if status {
				{
					err := handler.ExitAuthenticating(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.RetryState(ctx, data)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.EnterAuthenticating(ctx)
					if err != nil {
						return state, err
					}
				}
				return StateAuthenticating, nil
			}
		}
		{
			status, err := handler.CanRetryTransport(ctx, data)
			if err != nil {
				return state, err
			}
			if status {
				{
					err := handler.ExitAuthenticating(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.ExitConnecting(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.RetryTransport(ctx, data)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.EnterReady(ctx)
					if err != nil {
						return state, err
					}
				}
				return StateReady, nil
			}
		}
		{
			status, err := handler.CanRetryConnecting(ctx, data)
			if err != nil {
				return state, err
			}
			if status {
				{
					err := handler.ExitAuthenticating(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.ExitTransport(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.RetryConnecting(ctx, data)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.EnterDialing(ctx)
					if err != nil {
						return state, err
					}
				}
				return StateDialing, nil
			}
		}
		{
			err := handler.ExitAuthenticating(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.RetrySession(ctx, data)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateReady:
		{
			status, err := handler.CanRetryTransport(ctx, data)
			if err != nil {
				return state, err
			}
			if status {
				{
					err := handler.ExitReady(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.RetryTransport(ctx, data)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.EnterReady(ctx)
					if err != nil {
						return state, err
					}
				}
				return StateReady, nil
			}
		}
		{
			err := handler.ExitReady(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.RetrySession(ctx, data)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateDraining:
		{
			status, err := handler.CanRetryTransport(ctx, data)
			if err != nil {
				return state, err
			}
			if status {
				{
					err := handler.ExitDraining(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.RetryTransport(ctx, data)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.EnterReady(ctx)
					if err != nil {
						return state, err
					}
				}
				return StateReady, nil
			}
		}
		{
			err := handler.ExitDraining(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.RetrySession(ctx, data)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateOffline:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Restart" action and returns the destination state or an error.
func HandleRestart(ctx context.Context, handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateDialing:
		{
			err := handler.ExitDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateAuthenticating:
		{
			err := handler.ExitAuthenticating(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateReady:
		{
			err := handler.ExitReady(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateDraining:
		{
			err := handler.ExitDraining(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateOffline:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Reset" action and returns the destination state or an error.
func HandleReset(ctx context.Context, handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateDialing:
		{
			err := handler.ExitDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ResetSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateAuthenticating:
		{
			err := handler.ExitAuthenticating(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ResetSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateReady:
		{
			err := handler.ExitReady(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ResetSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateDraining:
		{
			err := handler.ExitDraining(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ResetSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateDialing, nil
	case StateOffline:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Refresh" action and returns the destination state or an error.
func HandleRefresh(ctx context.Context, handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateAuthenticating:
		{
			status, err := handler.CanRefresh(ctx)
			if err != nil {
				return state, err
			}
			if status {
				{
					err := handler.ExitAuthenticating(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.ExitConnecting(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.EnterReady(ctx)
					if err != nil {
						return state, err
					}
				}
				return StateReady, nil
			}
		}
		return state, runtime.ErrNoTransition
	case StateReady:
		{
			err := handler.ExitReady(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterReady(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateReady, nil
	case StateDraining:
		{
			status, err := handler.CanRefresh(ctx)
			if err != nil {
				return state, err
			}
			if status {
				{
					err := handler.ExitDraining(ctx)
					if err != nil {
						return state, err
					}
				}
				{
					err := handler.EnterReady(ctx)
					if err != nil {
						return state, err
					}
				}
				return StateReady, nil
			}
		}
		return state, runtime.ErrNoTransition
	case StateOffline, StateDialing:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Close" action and returns the destination state or an error.
func HandleClose(ctx context.Context, handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateDialing:
		{
			err := handler.ExitDialing(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterOffline(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateOffline, nil
	case StateAuthenticating:
		{
			err := handler.ExitAuthenticating(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitConnecting(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterOffline(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateOffline, nil
	case StateReady:
		{
			err := handler.ExitReady(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterOffline(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateOffline, nil
	case StateDraining:
		{
			err := handler.ExitDraining(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitTransport(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.ExitSession(ctx)
			if err != nil {
				return state, err
			}
		}
		{
			err := handler.EnterOffline(ctx)
			if err != nil {
				return state, err
			}
		}
		return StateOffline, nil
	case StateOffline:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}
