// Code generated by hsm/codegen. DO NOT EDIT.
//
// This file can be regenerated by running
// go run github.com/arnavdugar/hsm/codegen -i=machine.yaml -o=machine.go

package orderfulfillment

import "github.com/arnavdugar/hsm/runtime"

type ActionType int

const (
	ActionShip     ActionType = 1
	ActionPickUp   ActionType = 2
	ActionCancel   ActionType = 3
	ActionDispatch ActionType = 4
	ActionDeliver  ActionType = 5
	ActionCollect  ActionType = 6
)

type StateType int

const (
	StatePaid           StateType = 1
	StatePacking        StateType = 2
	StateShipped        StateType = 3
	StateReadyForPickup StateType = 4
	StateCompleted      StateType = 5
	StateCancelled      StateType = 6
)

type Handler interface {
}

// Handles an action and returns the destination state or an error.
func Handle(handler Handler, state StateType, action ActionType, data any) (StateType, error) {
	switch action {
	case ActionShip:
		return HandleShip(handler, state)
	case ActionPickUp:
		return HandlePickUp(handler, state)
	case ActionCancel:
		return HandleCancel(handler, state)
	case ActionDispatch:
		return HandleDispatch(handler, state)
	case ActionDeliver:
		return HandleDeliver(handler, state)
	case ActionCollect:
		return HandleCollect(handler, state)
	default:
		return state, runtime.ErrUnknownAction
	}
}

// Handles a "Ship" action and returns the destination state or an error.
func HandleShip(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StatePaid:
		return StatePacking, nil
	case StatePacking, StateShipped, StateReadyForPickup, StateCompleted, StateCancelled:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "PickUp" action and returns the destination state or an error.
func HandlePickUp(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StatePaid:
		return StateReadyForPickup, nil
	case StatePacking, StateShipped, StateReadyForPickup, StateCompleted, StateCancelled:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Cancel" action and returns the destination state or an error.
func HandleCancel(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StatePaid:
		return StateCancelled, nil
	case StatePacking:
		return StateCancelled, nil
	case StateReadyForPickup:
		return StateCancelled, nil
	case StateShipped, StateCompleted, StateCancelled:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Dispatch" action and returns the destination state or an error.
func HandleDispatch(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StatePacking:
		return StateShipped, nil
	case StatePaid, StateShipped, StateReadyForPickup, StateCompleted, StateCancelled:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Deliver" action and returns the destination state or an error.
func HandleDeliver(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateShipped:
		return StateCompleted, nil
	case StatePaid, StatePacking, StateReadyForPickup, StateCompleted, StateCancelled:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Collect" action and returns the destination state or an error.
func HandleCollect(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateReadyForPickup:
		return StateCompleted, nil
	case StatePaid, StatePacking, StateShipped, StateCompleted, StateCancelled:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}
