// Code generated by hsm/codegen. DO NOT EDIT.
//
// This file can be regenerated by running
// go run github.com/arnavdugar/hsm/codegen -i=machine.yaml -o=machine.go

package atm

import "github.com/arnavdugar/hsm/runtime"

type ActionType int

const (
	ActionCheckBalance ActionType = 1
	ActionWithdraw     ActionType = 2
	ActionDeposit      ActionType = 3
	ActionExit         ActionType = 4
	ActionDone         ActionType = 5
	ActionSubmit       ActionType = 6
	ActionCancel       ActionType = 7
	ActionApprove      ActionType = 8
	ActionDecline      ActionType = 9
)

type StateType int

const (
	StateMenu                StateType = 1
	StateBalance             StateType = 2
	StateEnterAmount         StateType = 3
	StateAuthorizeWithdrawal StateType = 4
	StateDispenseCash        StateType = 5
	StateAcceptDeposit       StateType = 6
	StateEnded               StateType = 7
)

type Handler interface {
}

// Handles an action and returns the destination state or an error.
func Handle(handler Handler, state StateType, action ActionType, data interface{}) (StateType, error) {
	switch action {
	case ActionCheckBalance:
		return HandleCheckBalance(handler, state)
	case ActionWithdraw:
		return HandleWithdraw(handler, state)
	case ActionDeposit:
		return HandleDeposit(handler, state)
	case ActionExit:
		return HandleExit(handler, state)
	case ActionDone:
		return HandleDone(handler, state)
	case ActionSubmit:
		return HandleSubmit(handler, state)
	case ActionCancel:
		return HandleCancel(handler, state)
	case ActionApprove:
		return HandleApprove(handler, state)
	case ActionDecline:
		return HandleDecline(handler, state)
	default:
		return state, runtime.ErrUnknownAction
	}
}

// Handles a "CheckBalance" action and returns the destination state or an error.
func HandleCheckBalance(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateMenu:
		return StateBalance, nil
	case StateBalance, StateEnterAmount, StateAuthorizeWithdrawal, StateDispenseCash, StateAcceptDeposit, StateEnded:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Withdraw" action and returns the destination state or an error.
func HandleWithdraw(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateMenu:
		return StateEnterAmount, nil
	case StateBalance, StateEnterAmount, StateAuthorizeWithdrawal, StateDispenseCash, StateAcceptDeposit, StateEnded:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Deposit" action and returns the destination state or an error.
func HandleDeposit(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateMenu:
		return StateAcceptDeposit, nil
	case StateBalance, StateEnterAmount, StateAuthorizeWithdrawal, StateDispenseCash, StateAcceptDeposit, StateEnded:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Exit" action and returns the destination state or an error.
func HandleExit(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateMenu:
		return StateEnded, nil
	case StateBalance, StateEnterAmount, StateAuthorizeWithdrawal, StateDispenseCash, StateAcceptDeposit, StateEnded:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Done" action and returns the destination state or an error.
func HandleDone(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateBalance:
		return StateMenu, nil
	case StateDispenseCash:
		return StateMenu, nil
	case StateAcceptDeposit:
		return StateMenu, nil
	case StateMenu, StateEnterAmount, StateAuthorizeWithdrawal, StateEnded:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Submit" action and returns the destination state or an error.
func HandleSubmit(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateEnterAmount:
		return StateAuthorizeWithdrawal, nil
	case StateMenu, StateBalance, StateAuthorizeWithdrawal, StateDispenseCash, StateAcceptDeposit, StateEnded:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Cancel" action and returns the destination state or an error.
func HandleCancel(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateEnterAmount:
		return StateMenu, nil
	case StateAcceptDeposit:
		return StateMenu, nil
	case StateMenu, StateBalance, StateAuthorizeWithdrawal, StateDispenseCash, StateEnded:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Approve" action and returns the destination state or an error.
func HandleApprove(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateAuthorizeWithdrawal:
		return StateDispenseCash, nil
	case StateMenu, StateBalance, StateEnterAmount, StateDispenseCash, StateAcceptDeposit, StateEnded:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}

// Handles a "Decline" action and returns the destination state or an error.
func HandleDecline(handler Handler, state StateType) (StateType, error) {
	switch state {
	case StateAuthorizeWithdrawal:
		return StateMenu, nil
	case StateMenu, StateBalance, StateEnterAmount, StateDispenseCash, StateAcceptDeposit, StateEnded:
		return state, runtime.ErrNoTransition
	default:
		return state, runtime.ErrUnknownState
	}
}
